# -----------------------------------------------------------------------------
# project
# -----------------------------------------------------------------------------

variable "credentials" {
  description = "The JSON file generated by GCP when asking for a service account token"
  default     = "/code/credentials/gcp-key.json"
}

variable "project" {
  description = "The project to deploy to, if not set the default provider project is used."
  default     = "modules-terraform-013"
}

variable "region" {
  description = "Region for cloud resources"
  default     = "europe-west1"
}

variable "service_account" {
  description = "The service account email that is used to run Google Functions"
  default     = "test-lpiot@modules-terraform-013.iam.gserviceaccount.com"
}
